
/**
    Imports the C standard library.
    
    Mutable atomic references.

    @par Literals
    - `atomic()`

    @par Implements
    - fa_equal_t
    - fa_order_t
    - fa_copy_t
    - fa_destroy_t
    - fa_string_show_t

    @see
    - [Data structures](@ref DataStructures)
 */

module Std
{
    import "C" assert;
    import "C" complex;
    import "C" ctype;
    import "C" errno;
    import "C" fenv;
    import "C" float;
    import "C" inttypes;
    import "C" limits;
    import "C" locale;
    import "C" math;
    import "C" setjmp;
    import "C" signal;
    import "C" stdalign;
    import "C" stdarg;
    import "C" stdbool;
    import "C" stddef;
    import "C" stdint;
    import "C" stdio;
    import "C" stdlib;
    import "C" string;
    import "C" tgmath;
    import "C" time;
    import "C" wchar;
    import "C" wctype;

    /**
        A voice type
        This is the next line 
        This is the last one
     */
    type Vox = Void;
    type A   = Void;
    
    /**
        The identity function.
     */
    id : A -> A;
}